### ISSUE TITLE
PDF Viewer

### ISSUE THREAD

**Issue by alex1702** [scoute-dich/PDFCreator#2]
Can you please build a nice looking open source  PDF viewer APP?

**Comment by phuyuk** [comment]
In the meantime, have you tried 'Document Viewer' on F-Droid? It's mature and feature-rich - and there _is_ value in using an unrelated reader (or two), to verify a PDF's integrity and compatibility.

**Comment by alex1702** [comment]
Yes, no modern design. No Material design.

**Comment by scoute-dich** [comment]
I already made a material version of MuPdf with material design: https://github.com/scoute-dich/MuPDF

**Comment by scoute-dich** [comment]
You can download an apk on the xda threat: http://forum.xda-developers.com/android/apps-games/app-mupdf-material-design-source-t3415158/page1

**Comment by alex1702** [comment]
nice why not in fdroid?

**Comment by scoute-dich** [comment]
Several reasons:
- because it's a fork I should rename all packages (a lot of work with every update)
- I only want my "own" apps on f-droid
- I don't have the time to maintain such apps

I think if they were on f-droid a lot of people would report issues, which I couldn't solve, because the reported problems would be problems of the original app. I only changed the theme and removed some not working features.

**Comment by alex1702** [comment]
OK thats right. Pull-request? 
Mäh cant install the app.

**Comment by scoute-dich** [comment]
I don't think that a pullrequest makes sense, since my fork requires at least Lollipop. So many users couldn't use it.

**Comment by alex1702** [comment]
Oh OK shit. So create your own viewer APP? xD
